version: "3.8"
services:
  backend:
    build:
      context: .
      target: runtime
    environment:
      - APP_CONFIG=production
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app.main:create_app()"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    # do NOT mount source code here (image-only)