version: "3.8"
services:
  backend:
    build: .
    volumes:
      - ./backend:/app/backend:rw
      - ./.env:/app/backend/.env:ro
    environment:
      - APP_CONFIG=development
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=5000
    command: sh -c "cd /app/backend && python -m app.main"
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5