name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r email-classifier-app/requirements.txt

      - name: Run unit tests (pytest)
        run: pytest -q
        working-directory: email-classifier-app

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm ci
        working-directory: email-classifier-app

      - name: Run Cypress E2E (headless Chrome)
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://127.0.0.1:5000'
          wait-on-timeout: 120000
          working-directory: './email-classifier-app'
          browser: chrome
        env:
          FLASK_APP: app